module.exports = Badge = () => ({
  ".badge, .prose a.badge": {
    borderRadius: "9999px",
    display: "inline-flex",
    alignItems: "center",
    fontWeight: 600,
    fontSize: "0.75rem",
    lineHeight: ["1rem", 1],
    overflow: "hidden",
    paddingTop: "0.25rem",
    paddingBottom: "0.25rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    position: "relative",
    textAlign: "center",
    textDecoration: "none",
    verticalAlign: "baseline",
    whiteSpace: "nowrap",
    width: "auto",
    transitionProperty: "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDuration: "150ms",
  },
  "a.badge:focus": {
    outline: "2px solid transparent",
    outlineOffset: "2px",
    "--tw-ring-offset-shadow": "var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color)",
    "--tw-ring-shadow": "var(--tw-ring-inset) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color)",
    boxShadow: "var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000)",
  },
  ".badge .btn": {
    borderWidth: "0px !important",
    marginLeft: "0.25rem !important",
    marginRight: "-0.25rem !important",
    padding: "0px !important",
  },
});
