module.exports = Dropdown = () => ({
  ".dropdown-list": {
    "--tw-bg-opacity": "1",
    backgroundColor: "rgba(255, 255, 255, var(--tw-bg-opacity))",
    "--tw-border-opacity": "1",
    borderColor: "rgba(241, 245, 249, var(--tw-border-opacity))",
    borderRadius: "0.25rem",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    flexDirection: "column",
    marginBottom: "0px",
    padding: "0.5rem",
    position: "absolute",
    "--tw-shadow": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    boxShadow: "var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow)",
    width: "12rem",
    zIndex: 10,
    transformOrigin: "top",
    transitionProperty: "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDuration: "150ms",
  },
  ".dropdown-item:hover": {
    "--tw-bg-opacity": "1",
    backgroundColor: "rgba(241, 245, 249, var(--tw-bg-opacity))",
  },
  ".dropdown-item:focus": {
    "--tw-bg-opacity": "1",
    backgroundColor: "rgba(241, 245, 249, var(--tw-bg-opacity))",
    outline: "2px solid transparent",
    outlineOffset: "2px",
    "--tw-ring-offset-shadow": "var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color)",
    "--tw-ring-shadow": "var(--tw-ring-inset) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color)",
    boxShadow: "var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow, 0 0 #0000)",
  },
  ".dropdown-item": {
    borderRadius: "0.25rem",
    display: "flex",
    alignItems: "center",
    fontWeight: 500,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    paddingTop: "0.25rem",
    paddingBottom: "0.25rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    position: "relative",
    "--tw-text-opacity": "1",
    color: "rgba(30, 41, 59, var(--tw-text-opacity))",
    textDecoration: "none",
    whiteSpace: "nowrap",
    width: "100%",
  },
  ".dropdown-item svg": {
    height: "1rem",
    "--tw-text-opacity": "1",
    color: "rgba(100, 116, 139, var(--tw-text-opacity))",
    width: "1rem",
  },
  "a.dropdown-item, .prose a.dropdown-item": { textDecoration: "none" },
  ".dropdown-arrow": {
    marginTop: "-3px",
    display: "inline",
    flex: "none",
    height: "1rem",
    marginLeft: "0.25rem",
    marginRight: "-0.25rem",
    color: "currentColor",
    verticalAlign: "middle",
    width: "1rem",
    "--tw-translate-x": "0",
    "--tw-translate-y": "0",
    "--tw-rotate": "0",
    "--tw-skew-x": "0",
    "--tw-skew-y": "0",
    "--tw-scale-x": "1",
    "--tw-scale-y": "1",
    transform:
      "translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))",
    transitionProperty: "background-color, border-color, color, fill, stroke, opacity, box-shadow, transform",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDuration: "150ms",
  },
  ".btn-sm .dropdown-arrow": { marginLeft: "0px" },
  ".btn-lg .dropdown-arrow": {
    height: "1.5rem !important",
    width: "1.5rem !important",
  },
  ".dropdown-divide": {
    "--tw-border-opacity": "1",
    borderColor: "rgba(226, 232, 240, var(--tw-border-opacity))",
    borderStyle: "solid",
    borderTopWidth: "1px",
    marginTop: "0.5rem",
    marginBottom: "0.5rem",
    marginRight: "-0.5rem",
    marginLeft: "-0.5rem",
  },
  ".dropdown-header": {
    fontWeight: 700,
    fontSize: "0.75rem",
    lineHeight: ["1rem", 1],
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    "--tw-text-opacity": "1",
    color: "rgba(148, 163, 184, var(--tw-text-opacity))",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    width: "100%",
  },
  ".prose .dropdown-header": { marginTop: "0px", marginBottom: "0px" },
  ".dropdown-sm .dropdown-item": { fontSize: "0.75rem", lineHeight: "1rem" },
  ".dropdown-sm .dropdown-list": { width: "10rem" },
  ".dropdown-sm .dropdown-header": { paddingLeft: "0px", paddingRight: "0px" },
  ".dropdown-lg .dropdown-item": {
    fontSize: "1.125rem",
    lineHeight: "1.75rem",
  },
  ".dropdown-lg .dropdown-list": { width: "16rem" },
});
