module.exports = Tooltip = () => ({
  ".tooltip": {
    "--tw-bg-opacity": "1",
    backgroundColor: "rgba(15, 23, 42, var(--tw-bg-opacity))",
    borderRadius: "0.25rem",
    fontWeight: 500,
    fontSize: "0.75rem",
    lineHeight: "1rem",
    maxWidth: "20rem",
    padding: "0.5rem",
    position: "absolute",
    top: "0px",
    left: "0px",
    textAlign: "center",
    "--tw-text-opacity": "1",
    color: "rgba(255, 255, 255, var(--tw-text-opacity))",
    overflowWrap: "break-word",
    zIndex: 50,
    "--tw-translate-x": "0",
    "--tw-translate-y": "0",
    "--tw-rotate": "0",
    "--tw-skew-x": "0",
    "--tw-skew-y": "0",
    "--tw-scale-x": "1",
    "--tw-scale-y": "1",
    transform:
      "translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))",
    transformOrigin: "center",
    willChange: "transform",
  },
});
